### ISSUE TITLE
errorThresholdPercentage does notwork as expected

### ISSUE THREAD

**Issue by GeminiWind** [nodeshift/opossum#404]
## Node.js Version:
v10.19.0

## Operating System:

Ubuntu 18.04 LTS

## Steps to Produce Error:

1. Create `httpHandler`

```javascript
import * as R from 'ramda';
import CircuitBreaker from 'opossum';
import JsonApiError, { RequestTimeoutError, ServiceUnavailableError } from 'json-api-error';

const getHeaders = R.pipe(
  r => R.pathOr({}, ['headers'], r),
  headers => R.mergeLeft(headers, {
    'Content-Type': 'application/vnd.api+json',
    Accept: 'application/vnd.api+json',
  }),
);

const onTimeout = () => {
  throw new RequestTimeoutError();
};
const onOpen = () => {
  throw new ServiceUnavailableError('Service is not available.Please try again');
};

const httpHandler = (fn, customCircuitBreakerOpts = {}) => async (req, res, next) => {
  try {
    const defaultCircuitBreakerOptions = {
      timeout: 5000, // If our function takes longer than 5 seconds, trigger a failure
      errorThresholdPercentage: 50, // When 50% of requests fail, trip the circuit
      resetTimeout: 10000, // After 10 seconds, try again.
      errorFilter: (error) => {
        if (error instanceof JsonApiError) {
          const serializedError = JSON.parse(JSON.stringify(error));
          if (serializedError.status.match(/^4[0-9]{2}$/)) {
            return true;
          }

          return false;
        }

        return false;
      },
    };

    const circuitBreakerOpts = R.mergeRight(defaultCircuitBreakerOptions, customCircuitBreakerOpts);
    const breaker = new CircuitBreaker(fn, circuitBreakerOpts);

    breaker.on('timeout', onTimeout);
    breaker.on('open', onOpen);

    const result = await breaker.fire(req);

    if (result) {
      const headers = getHeaders(result);

      res.set(headers).status(result.statusCode).json(result.body);
    }

    next();
  } catch (error) {
    next(error);
  }
};

export default httpHandler;
```

2. Testing  (with `Jest`)
- Test file
```javascript
import { RequestTimeoutError, BadRequestError, InternalError } from 'json-api-error';
import httpHandler from '../src/httpHandler';

describe('httpHandler', () => {
  const req = {
    headers: {
      accept: 'application/vnd.api+json',
      'content-type': 'application/vnd.api+json',
    },
    params: {
      userId: 1,
    },
  };

  const res = {
    set: jest.fn().mockImplementation(function () { return this; }),
    status: jest.fn().mockImplementation(function () { return this; }),
    json: jest.fn().mockImplementation(function () { return this; }),
  };

  const next = jest.fn().mockImplementation(error => error);

  afterEach(() => {
    jest.clearAllMocks();
  });

  it('return correct response with no response headers was set', async () => {
    const handler = request => ({
      statusCode: 200,
      body: {
        userId: request.params.userId,
      },
    });

    const transformer = httpHandler(handler);

    await transformer(req, res, next);

    expect(res.status.mock.calls[0][0]).toBe(200);
    expect(res.set.mock.calls[0][0]).toStrictEqual({ Accept: 'application/vnd.api+json', 'Content-Type': 'application/vnd.api+json' });
    expect(res.json.mock.calls[0][0]).toStrictEqual({
      userId: req.params.userId,
    });
  });

  it('return correct response with Accept & Content-Type response header was override default value', async () => {
    const handler = request => ({
      headers: {
        Accept: 'application/json',
        'Content-Type': 'application/json',
      },
      statusCode: 200,
      body: {
        userId: request.params.userId,
      },
    });

    const transformer = httpHandler(handler);

    await transformer(req, res, next);

    expect(res.status.mock.calls[0][0]).toBe(200);
    expect(res.set.mock.calls[0][0]).toStrictEqual({ Accept: 'application/json', 'Content-Type': 'application/json' });
    expect(res.json.mock.calls[0][0]).toStrictEqual({
      userId: req.params.userId,
    });
  });

  it('send BadRequestError to "next" function if it encounter BadRequestError in processing handler', async () => {
    const handler = () => { throw new BadRequestError('Your data is invalid'); };

    const transformer = httpHandler(handler);

    await transformer(req, res, next);

    expect(next.mock.calls.length).toBe(1);
    expect(next.mock.calls[0][0]).toBeInstanceOf(BadRequestError);
  });

  it('send InternalError to "next" function if it encounter InternalError in processing handler', async () => {
    const handler = () => { throw new InternalError('Oops! Something went wrong'); };

    const transformer = httpHandler(handler);

    await transformer(req, res, next);

    expect(next.mock.calls.length).toBe(1);
    expect(next.mock.calls[0][0]).toBeInstanceOf(InternalError);
  });
});

```
- Console
```
 httpHandler
    ✓ return correct response with no response headers was set (17ms)
    ✓ return correct response with Accept & Content-Type response header was override default value (3ms)
    ✓ send BadRequestError to "next" function if it encounter BadRequestError in processing handler (3ms)
    ✕ send InternalError to "next" function if it encounter InternalError in processing handler (5ms)

  ● httpHandler › send InternalError to "next" function if it encounter InternalError in processing handler

    expect(received).toBeInstanceOf(expected)

    Expected constructor: InternalError
    Received constructor: ServiceUnavailableError

      86 | 
      87 |     expect(next.mock.calls.length).toBe(1);
    > 88 |     expect(next.mock.calls[0][0]).toBeInstanceOf(InternalError);
         |                                   ^
      89 |   });
      90 | });
      91 | 

      at _callee4$ (tests/httpHandler.test.js:88:35)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:45:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:271:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:97:21)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:45:40)
      at invoke (node_modules/regenerator-runtime/runtime.js:135:20)
      at node_modules/regenerator-runtime/runtime.js:145:13
```

**Note**: `InternalError` after being serialized has status "500". Meanwhile, `BadRequestError` after being serialized has status "400"
3. Conclusion 
- **Expected**: the circuit breaker should keep state being closed and throw InternalError because there 's only 1 error (25%)
- **Actual**: the circuit breaker changed state to open and thow `ServiceUnavailableError`

**Comment by GeminiWind** [comment]
This is my bad in code for creating new circuit breaker each `httpHandler` was invoked
