### ISSUE TITLE
I think there is a problem with my implementation. Can you help me?

### ISSUE THREAD

**Issue by maxinuss** [nodeshift/opossum#470]
I would like to implement CB and bypass Redis key getters in my app if Redis response time is too high or if Redis server is down.

I'm using Opossum CB library: https://github.com/nodeshift/opossum

I'm testing with ideal conditions, and the idea is to get a proper json response, but I got an Exception.

This is actually my (simplified) endpoint code:

```javascript
router.get('/news', async (req: any, res: any) => {
    const { query } = req

    try {
      const keyHash = `user:${query.userId}`

      const cached = await getRedisKey(redisClient, keyHash)
      if (cached) {
        return res.status(200).json(JSON.parse(cached))
      }

      const result = await getNews(query.userId)

      // Save it when you can, don't need to await.
      setRedisKey(redisClient, keyHash, JSON.stringify(result)).then()

      res.status(200).json(result)
    } catch (e) {
      res.status(400).json(e.message)
    }
  })
```

And this is my CB implementation inside getRedisKey method.
Is not complete... the idea is to add a Fallback with a false return if the circuit is open, but at this moment I want to test if with the circuit closed it works... but not :-(.

Just as note if I return client.get(hash) the response works great. So this is a problem with my CB implementation.

```javascript
import CircuitBreaker from 'opossum'

export const getRedisKey = async (client: any, hash: string): Promise<any> => {
  const OPTIONS = {
    timeout: 1000, // If our function takes longer than 1 seconds, trigger a failure
    errorThresholdPercentage: 50, // When 50% of requests fail, trip the circuit
    resetTimeout: 30000, // After 30 seconds, try again.
  }

  try {
    const breaker = new CircuitBreaker(client.get, OPTIONS)
    return breaker.fire(hash)
  } catch (e) {
    log(`Error getting from redis ${JSON.stringify(e)}`, e)
  }
}
```

I'm getting this error: 
```
node-container | Error getting from redis {} TypeError: Cannot read property 'dropBufferSupport' of undefined
node-container |     at Function.<anonymous> (/www/node_modules/ioredis/built/commander.js:110:26)
node-container |     at /www/node_modules/opossum/lib/circuit.js:521:38
node-container |     at new Promise (<anonymous>)
node-container |     at CircuitBreaker.call (/www/node_modules/opossum/lib/circuit.js:497:12)
node-container |     at CircuitBreaker.fire (/www/node_modules/opossum/lib/circuit.js:415:22)
node-container |     at Object.exports.getRedisKey (/www/src/services/RedisService.ts:41:26)
node-container |     at /www/src/routes.ts:27:31
node-container |     at Layer.handle [as handle_request] 
(/www/node_modules/express/lib/router/layer.js:95:5)
node-container |     at next (/www/node_modules/express/lib/router/route.js:137:13)
node-container |     at Route.dispatch (/www/node_modules/express/lib/router/route.js:112:3)
node-container |     at Layer.handle [as handle_request] (/www/node_modules/express/lib/router/layer.js:95:5)
node-container |     at /www/node_modules/express/lib/router/index.js:281:22
node-container |     at Function.process_params (/www/node_modules/express/lib/router/index.js:335:12)
node-container |     at next (/www/node_modules/express/lib/router/index.js:275:10)
node-container |     at Function.handle (/www/node_modules/express/lib/router/index.js:174:3)
node-container |     at router (/www/node_modules/express/lib/router/index.js:47:12)
node-container |     at Layer.handle [as handle_request] (/www/node_modules/express/lib/router/layer.js:95:5)
node-container |     at trim_prefix (/www/node_modules/express/lib/router/index.js:317:13)
node-container |     at /www/node_modules/express/lib/router/index.js:284:7 user:1

```

**Comment by lance** [comment]
Hi @maxinuss - you should be creating a single circuit breaker outside of the function instead of creating a new one each time the function is called.

```js
import CircuitBreaker from 'opossum'
const breaker = new CircuitBreaker(client.get, OPTIONS)

export const getRedisKey = async (client: any, hash: string): Promise<any> => {
  const OPTIONS = {
    timeout: 1000, // If our function takes longer than 1 seconds, trigger a failure
    errorThresholdPercentage: 50, // When 50% of requests fail, trip the circuit
    resetTimeout: 30000, // After 30 seconds, try again.
  }

  try {
    return breaker.fire(hash)
  } catch (e) {
    log(`Error getting from redis ${JSON.stringify(e)}`, e)
  }
}
```

I'm honestly not sure if this will solve your issue. But it's definitely something you should adjust in your code. Your error seems unrelated to that. Try making this change, and if it still is failing is there a way you could provide a reproducible test case? Thanks.

**Comment by maxinuss** [comment]
Thank you @lance in fact, that was the problem.
I solved it by putting these code outside the function and I replaced the CB instance from "client.get" to "getRedisKey"

Is working in this way:

```javascript

const BREAKER_OPTIONS = {
  timeout: 1000, // If our function takes longer than 1 seconds, trigger a failure
  errorThresholdPercentage: 50, // When 50% of requests fail, trip the circuit
  resetTimeout: 30000, // After 30 seconds, try again.
}

const breaker = new CircuitBreaker(getRedisKey, BREAKER_OPTIONS)

...

router.get('/news', async (req: any, res: any) => {
    const { query } = req

    try {
      const keyHash = `user:${query.userId}`

      const cached = await breaker.fire(redisClient, keyHash)  <--here I fire it
      if (cached) {
        return res.status(200).json(JSON.parse(cached))
      }

      const result = await getNews(query.userId)

      // Save it when you can, don't need to await.
      setRedisKey(redisClient, keyHash, JSON.stringify(result)).then()

      res.status(200).json(result)
    } catch (e) {
      res.status(400).json(e.message)
    }
  })

...

```

And I left getRedisKey in this way:

```javascript
export const getRedisKey = async (client: any, hash: string): Promise<any> => {
  try {
    return client.get(hash)
  } catch (e) {
    log(`Error getting from redis ${JSON.stringify(e)}`, e)
  }
}
```

Thank you for your time you saved me!

**Comment by lance** [comment]
@maxinuss that's great! Glad it worked.
